package cm.uds.fuchsia.gag.model.configuration;

import cm.uds.fuchsia.gag.model.specification.Parameter;
import cm.uds.fuchsia.gag.util.NameGenerator;

public class Data {
	private Object value;
	private Parameter parameter;
	
	private String name ;//generated by the name generator

	public Data() {
		name=NameGenerator.newName();
	}
	public Object getValue() {
		return value;
	}

	public void setValue(Object value) {
		this.value = value;
	}

	public Parameter getParameter() {
		return parameter;
	}
	
	public void setParameter(Parameter parameter) {
		this.parameter = parameter;
	}

	public String getName() {
		return name;
	}

/*
	public void setName(String name) {
		this.name = name;
	}
*/	
	

}
